/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StageResponse = IDL.Record({
  'option' : IDL.Text,
  'feeling' : IDL.Text,
  'response' : IDL.Text,
  'category' : IDL.Text,
  'impulseStrength' : IDL.Text,
  'reason' : IDL.Text,
});
export const Time = IDL.Int;
export const CompletedSession = IDL.Record({
  'timing' : IDL.Text,
  'stageResponses' : IDL.Vec(StageResponse),
  'timestamp' : Time,
  'outcome' : IDL.Text,
  'actionTitle' : IDL.Text,
  'finalDecision' : IDL.Text,
});
export const CategoryResults = IDL.Record({
  'habit' : IDL.Nat,
  'social' : IDL.Nat,
  'emotion' : IDL.Nat,
  'productivity' : IDL.Nat,
  'convenience' : IDL.Nat,
  'reason' : IDL.Nat,
  'health' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllSessions' : IDL.Func(
      [],
      [
        IDL.Record({
          'sortedByTimestamp' : IDL.Vec(CompletedSession),
          'allSessions' : IDL.Vec(IDL.Tuple(IDL.Text, CompletedSession)),
        }),
      ],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryAnalysis' : IDL.Func([], [CategoryResults], ['query']),
  'getRecentSessions' : IDL.Func([], [IDL.Vec(CompletedSession)], ['query']),
  'getReconsiderationRate' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveSession' : IDL.Func(
      [IDL.Text, IDL.Vec(StageResponse), IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StageResponse = IDL.Record({
    'option' : IDL.Text,
    'feeling' : IDL.Text,
    'response' : IDL.Text,
    'category' : IDL.Text,
    'impulseStrength' : IDL.Text,
    'reason' : IDL.Text,
  });
  const Time = IDL.Int;
  const CompletedSession = IDL.Record({
    'timing' : IDL.Text,
    'stageResponses' : IDL.Vec(StageResponse),
    'timestamp' : Time,
    'outcome' : IDL.Text,
    'actionTitle' : IDL.Text,
    'finalDecision' : IDL.Text,
  });
  const CategoryResults = IDL.Record({
    'habit' : IDL.Nat,
    'social' : IDL.Nat,
    'emotion' : IDL.Nat,
    'productivity' : IDL.Nat,
    'convenience' : IDL.Nat,
    'reason' : IDL.Nat,
    'health' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllSessions' : IDL.Func(
        [],
        [
          IDL.Record({
            'sortedByTimestamp' : IDL.Vec(CompletedSession),
            'allSessions' : IDL.Vec(IDL.Tuple(IDL.Text, CompletedSession)),
          }),
        ],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryAnalysis' : IDL.Func([], [CategoryResults], ['query']),
    'getRecentSessions' : IDL.Func([], [IDL.Vec(CompletedSession)], ['query']),
    'getReconsiderationRate' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveSession' : IDL.Func(
        [IDL.Text, IDL.Vec(StageResponse), IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };