/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CategoryResults {
  'habit' : bigint,
  'social' : bigint,
  'emotion' : bigint,
  'productivity' : bigint,
  'convenience' : bigint,
  'reason' : bigint,
  'health' : bigint,
}
export interface CompletedSession {
  'timing' : string,
  'stageResponses' : Array<StageResponse>,
  'timestamp' : Time,
  'outcome' : string,
  'actionTitle' : string,
  'finalDecision' : string,
}
export interface StageResponse {
  'option' : string,
  'feeling' : string,
  'response' : string,
  'category' : string,
  'impulseStrength' : string,
  'reason' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllSessions' : ActorMethod<
    [],
    {
      'sortedByTimestamp' : Array<CompletedSession>,
      'allSessions' : Array<[string, CompletedSession]>,
    }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryAnalysis' : ActorMethod<[], CategoryResults>,
  'getRecentSessions' : ActorMethod<[], Array<CompletedSession>>,
  'getReconsiderationRate' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveSession' : ActorMethod<
    [string, Array<StageResponse>, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];